### PR TITLE
recreate image tags on target

### PR DESCRIPTION
**Pull request by lelmarir**

### CODE REVIEW

**Review by mkantor — COMMENTED** [review]
I'm not sure about this feature. I want to keep the behavior similar to a normal docker push/pull, and those commands don't recreate tags.

@lelmarir, what's your use case for this?

**Comment by lelmarir** [comment]
my use case: if i push a new image on a remote it will be pushed as "image:latest" and i lost the tag with the version, and i can't be sure if i've pushed the last one (coming back later)

plese take a look at the commit '--push-all-tags switch' (https://github.com/mkantor/docker-pushmi-pullyu/pull/9/commits/8afe2ebc8c6ed0a6e75f7a4ff46ab1b58d3e3301)
i've added this as a switch "--push-all-tags". This way the default behaviour(without the switch) would keep the normal docker behaviour

**Comment by mkantor** [comment]
@lelmarir I still don't fully understand why this is necessary. Could your use case be handled the same way it would with `docker push`, by specifying the version tag on the CLI? For example, `docker-pushmi-pullyu foo:1.2.3 user@host` should create an image named `foo` that is tagged `1.2.3` on the remote host (if it doesn't then there's a bug; it works for me).

I'll change the usage output to be more consistent with `docker push` and `docker pull` so that it's obvious that you can specify tags as mentioned above (e.g. `docker-pushmi-pullyu NAME[:TAG] ...`). See #14.

**Comment by lelmarir** [comment]
"docker-pushmi-pullyu foo:1.2.3 user@host" should work,
but in my case i just need to push the latest image and i'd need to look for the latest version tag "1.2.3".
even if i do, on the remote i still get foo:1.2.3 not tagged as latest, and i need to tag it manually

in my use case it is for convenience, but i can think about another use case:
take for example the tomcat image and its tags: _8.0.42-jre7, 8.0-jre7, 8-jre7, jre7, 8.0.42, 8.0, 8, latest_
as you can see it has multiple tags, and if i'm using tomcat:8-jre7 for a container on the remote host and tomcat:latest on another, i need to push these tags.

If i'd use the image from a remote repository (registry/tomcat:latest) it would check for updates and download the new image associated with the tag, but with docker-pushmi-pullyu you are reasoning from the other side: you must push all tags to the remote

**Comment by mkantor** [comment]
@lelmarir sorry I keep bugging you about this one. Can you explain how your example workflows would look if you didn't have docker-pushmi-pullyu and were instead using `docker push` and `docker pull` with a registry?

**Comment by lelmarir** [comment]
no problem,
suppose i have multiple docker hosts.
I've just finished a new image, tagged with myimage:1.2.4
`docker push myrepo\myimage`
now i need to test this image on a host
`docker pull myrepo\myimage;
docker run myrepo\myimage`
the day after, if it works i can repeat this on other hosts
`docker pull myrepo\myimage;
docker run myrepo\myimage`
docker pull will check for me if i have the latest image

with docker-pushmi-pullyu i don't relay on a repository, so i can't check that the image i have on the host is the latest one (i'd have to compare the image ids)
instead, if i also push all the image tags i can immediately see if the "latest" tagged image is the one i need (the one with the "1.2.4" tag)

I dont really see docker-pushmi-pullyu as a replacement for a repository, but more similar to 
`docker save;
docker load`

I hope I'm making myself clear

**Comment by mkantor** [comment]
Closing this for housekeeping purposes.

**Pull request closed without merging**
